# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cmetry < Formula
    desc "Chronometry CLI"
    homepage "https://github.com/ant4g0nist/chronometry"
    version "0.9.5"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/ant4g0nist/chronometry/releases/download/v0.9.5/chronometry_Darwin_arm64.tar.gz"
        sha256 "942cb3ec5e172ab5276e8c5645bf4bfb928d7220fd13772156c85555865a1b05"
  
        def install
          bin.install "cmetry"
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/ant4g0nist/chronometry/releases/download/v0.9.5/chronometry_Darwin_x86_64.tar.gz"
        sha256 "f9aac38cf232495ecbae5279a4728c737d040c5a8b2872491bc9f3f51e4ffa28"
  
        def install
          bin.install "cmetry"
        end
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/ant4g0nist/chronometry/releases/download/v0.9.5/chronometry_Darwin_arm64.tar.gz"
        sha256 "38c5b5265ae15472dd1a2557856567fc830cac6479166931c1f9959714d49648"
  
        def install
          bin.install "cmetry"
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/ant4g0nist/chronometry/releases/download/v0.9.5/chronometry_Darwin_x86_64.tar.gz"
        sha256 "9a34365e5f39cf7783194dfd6fc958d69bcc40acfabf80bea722e188130ad7a6"
  
        def install
          bin.install "cmetry"
        end
      end
    end
  end
  