# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cmetry < Formula
    desc "Chronometry CLI"
    homepage "https://github.com/ant4g0nist/chronometry"
    version "0.9.5"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/ant4g0nist/chronometry/releases/download/v0.9.5/chronometry_Darwin_arm64.tar.gz"
        sha256 "ee2f617a70e3113e26ca29b2802979d7c22f5d216470e66ae8119bf42fb812ad"
  
        def install
          bin.install "cmetry"
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/ant4g0nist/chronometry/releases/download/v0.9.5/chronometry_Darwin_x86_64.tar.gz"
        sha256 "9352eb0307ea61bbacbc5615c97d4b41c87f590629e6ccf0f53d03c777af255a"
  
        def install
          bin.install "cmetry"
        end
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/ant4g0nist/chronometry/releases/download/v0.9.5/chronometry_Darwin_arm64.tar.gz"
        sha256 "a90b1597ce1de7546358307890134461b5005dff509c5f5446c1c1b083d8bcb9"
  
        def install
          bin.install "cmetry"
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/ant4g0nist/chronometry/releases/download/v0.9.5/chronometry_Darwin_x86_64.tar.gz"
        sha256 "94869ebd2e4d892e089b17c0a890a0bc68abc2871d5d43d76cb2fd9e5a65bfc6"
  
        def install
          bin.install "cmetry"
        end
      end
    end
  end
  